schema_version = "1.0.0"

id = "BlenderSFDI"
version = "0.1.0"

name = "BlenderSFDI"
tagline = "TODO: Add"

maintainer = "Daniel Weston <psydw2@nottingham.ac.uk>"
website = "https://github.com/DannyWeston/blender-sfdi"
license = [
  "SPDX:GPL-2.0-or-later",
]

type = "add-on"
platforms = ["windows-x64"]
blender_version_min = "4.3.0"

wheels = [
  "wheels/opensfdi-0.1.13-py3-none-any.whl",

  "wheels/contourpy-1.3.3-cp311-cp311-win_amd64.whl",
  "wheels/cycler-0.12.1-py3-none-any.whl",
  "wheels/fonttools-4.61.1-cp311-cp311-win_amd64.whl",
  "wheels/imageio-2.37.2-py3-none-any.whl",
  "wheels/joblib-1.5.3-py3-none-any.whl",
  "wheels/kiwisolver-1.4.9-cp311-cp311-win_amd64.whl",
  "wheels/lazy_loader-0.4-py3-none-any.whl",
  "wheels/matplotlib-3.10.8-cp311-cp311-win_amd64.whl",
  "wheels/memory_profiler-0.61.0-py3-none-any.whl",
  "wheels/networkx-3.6.1-py3-none-any.whl",
  "wheels/numpy-1.26.0-cp311-cp311-win_amd64.whl",
  "wheels/opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl",
  "wheels/packaging-26.0-py3-none-any.whl",
  "wheels/pillow-10.4.0-cp311-cp311-win_amd64.whl",
  "wheels/psutil-7.2.2-cp37-abi3-win_amd64.whl",
  "wheels/pygments-2.19.2-py3-none-any.whl",
  "wheels/pyparsing-3.3.2-py3-none-any.whl",
  "wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "wheels/scikit_image-0.24.0-cp311-cp311-win_amd64.whl",
  "wheels/scikit_learn-1.8.0-cp311-cp311-win_amd64.whl",
  "wheels/scipy-1.16.3-cp311-cp311-win_amd64.whl",
  "wheels/six-1.17.0-py2.py3-none-any.whl",
  "wheels/threadpoolctl-3.6.0-py3-none-any.whl",
  "wheels/tifffile-2026.1.28-py3-none-any.whl",
  "wheels/typing_extensions-4.15.0-py3-none-any.whl",
  "wheels/vedo-2025.5.4-py3-none-any.whl",
  "wheels/vtk-9.6.0-cp311-cp311-win_amd64.whl",
]

[permissions]
network = "For doing y"
files = "For doing z"
clipboard = "For doing x"